name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_TAG: $(echo $GITHUB_SHA | head -c7)-${{ github.date }}
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker login & build & push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_USERNAME }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-gitops:$DOCKER_TAG .
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-gitops:$DOCKER_TAG

    - name: generate release file
      run: |
        export IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/hello-gitops
        sed -i 's|$(cat .last_sucessful_build_img)|$IMAGE_NAME:$DOCKER_TAG|' $GITHUB_WORKSPACE/helm/values.yml
        echo $IMAGE_NAME:$DOCKER_TAG > .last_sucessful_build_img

    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        push-branch: 'main'
        commit-message: '[VERSION] bump version'
        files: .last_sucessful_build_img, ./helm/values.yml
        name: GitHub Action
        email: "action@github.com"
