name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: configuring environment variables
      run: |
        echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/hello-gitops" >> $GITHUB_ENV
        echo "DOCKER_TAG=$(cat .last_sucessful_build_img | head -c7)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/hello-gitops
        tags: ${{ env.DOCKER_TAG }}, latest

    - name: generate release file
      run: |

        sed -i 's|$(cat .last_sucessful_build_img)|${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}|' $GITHUB_WORKSPACE/helm/values.yml
        echo ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} > .last_sucessful_build_img

    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        push-branch: 'main'
        commit-message: '[VERSION] bump version'
        files: .last_sucessful_build_img, ./helm/values.yml
        name: GitHub Action
        email: "action@github.com"
