name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/hello-gitops
        tags: ${{ github.sha }}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: generate release file
      run: |
        echo ${{ github.sha }} > .VERSION

    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        push-branch: 'main'
        commit-message: '[VERSION] bump version'
        files: .VERSION
        name: GitHub Action
        email: "action@github.com"
